
SET MAXROCKETHEIGHT TO 20.
SET ALTRADARFILE TO "0:/altradar.txt".
SET HATCHOFFSET TO 0.

IF (ALT:RADAR < MAXROCKETHEIGHT) {
  IF EXISTS(ALTRADARFILE) {
    DELETEPATH(ALTRADARFILE).
  }
  CREATE(ALTRADARFILE).
  LOG ROUND(ALT:RADAR, 1) TO ALTRADARFILE.
  SET HATCHOFFSET TO ALT:RADAR.
}

ELSE {
  SET HATCHOFFSET TO OPEN(ALTRADARFILE):READALL:STRING:TOSCALAR.
}

PRINT "Crew hatch offset:" + HATCHOFFSET + " metres".  
